### ISSUE TITLE
Authorization page should be https://app.medplum.com/oauth2/authorize not https://app.medplum.com/oauth

### ISSUE THREAD

**Issue by yurycodex** [medplum/medplum#1210]
When I open the page in browser
```
https://app.medplum.com/oauth2/authorize?client_id=value_here&redirect_uri= value_here&response_type=code&scope=openid&code_challenge_method=S256&code_challenge=Eemm0cdyGVV7Nyl9ueXPcYwwO4pZpUYJkXeEqmXPZf4
```
It says `the resource not found`
it works with 
```
https://app.medplum.com/oauth?client_id=value_here&redirect_uri= value_here&response_type=code&scope=openid&code_challenge_method=S256&code_challenge=Eemm0cdyGVV7Nyl9ueXPcYwwO4pZpUYJkXeEqmXPZf4
```
based on this documentation:
https://fhir.epic.com/Documentation?docId=oauth2
we expect that sign in page will be `https://app.medplum.com/oauth2/authorize` not  `https://app.medplum.com/oauth`

**Comment by codyebberson** [comment]
Hi @yurycodex 

We support the `/oauth2/authorize` endpoint on the API server. I.e., `https://api.medplum.com/oauth2/authorize` -- note `api` vs `app`.

Learn more here: https://www.medplum.com/docs/api/oauth/authorize

`https://api.medplum.com/oauth2/authorize` validates parameters and does one of 4 things:
1. On invalid configuration, show an error message
2. On client error, redirect back to the client application
3. If the user has an active session, directly redirect to the `redirect_uri`
4. Otherwise redirect to the signin page, typically at `https://app.medplum.com/oauth`

Can you try to use `https://api.medplum.com/oauth2/authorize` to see if that behaves as expected?

**Comment by codyebberson** [comment]
Resolved in Discord
