### ISSUE TITLE
Implement FHIR search _include

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1298]
Related to #1288

**Comment by arscan** [comment]
I was trying out the [Inferno US Core tests](https://github.com/inferno-framework/us-core-test-kit) (which are imported into the Inferno (g)(10) tests) using a test data set that we created and it failed because our data set happens to use Medication references in the MedicationRequest resource, instead of just providing a code.  In this case, the server needs to support _include searches: https://www.hl7.org/fhir/us/core/CapabilityStatement-us-core-client.html#medicationrequest

> The MedicationRequest resources can represent a medication using either a code or refer to the Medication resource. When referencing Medication, the resource may be [contained](http://hl7.org/fhir/R4/references.html#contained) or an external resource. The server application MAY choose any one way or more than one method, but if an external reference to Medication is used, the server SHALL support the _include` parameter for searching this element. The client application must support all methods.

Just FYI in case you are looking for a concrete case where this is needed and an external client that is looking for it.

**Comment by reshmakh** [comment]
Thanks for this feedback @arscan!  This is really useful.  We are [very familiar](https://youtu.be/pqe9AREZh-I) with the Inferno US Core tests.  Quick question - you don't happen to publish that test data set do you?  We created our own - and wondered if there was a good one out there.

**Comment by arscan** [comment]
I used [patient 1](https://raw.githubusercontent.com/inferno-framework/inferno-reference-server/master/us-core-r4-resources/d831ec91-c7a3-4a61-9312-7ff0c4a32134.json) and [patient 2](https://raw.githubusercontent.com/inferno-framework/inferno-reference-server/master/us-core-r4-resources/e91975f5-9445-c11f-cabf-c3c6dae161f2.json), which combine to include at least one example of every element tagged as 'must support' in US Core v3.11, v4, v5.  It also has a couple of edge cases (like this Medication one, to make sure our tests could handle them).  They are what we have loaded up on https://inferno.healthit.gov/reference-server/r4

Note that one of them is > 1mb, so you have to remove whitespace padding in order to make it uploadable to the default config of the medplum api server.  I assume there is a config setting I could have used to remove that 1mb constraint on my own installation?

We generated these patients using a script that runs Synthea and tries to create good testing data sets based on the output (realistic, valid, complete US Core coverage, not too big).  See https://github.com/inferno-framework/uscore-data-script.  We still have an outstanding PR to upgrade this to US Core v4, v5 that we haven't had a chance to wrap up.  The patient records I linked above were manually updated for US Core v4, v5 due to time constraints.

**Comment by julienblin** [comment]
+1 - voting for this issue as well - at EnSage we would benefit from having `_include` support in the API (including the `:iterate` option).

Thanks!

**Comment by reshmakh** [comment]
@plauclair, @julienblin, @arscan - thanks so much for this.  Will keep you updated on the progress.  @plauclair - can you spell out the query you are making?  Maybe @rahul1 or I have an idea on a workaround.

**Comment by julienblin** [comment]
@reshmakh - thanks for the follow-up. We have the use case everywhere, but here is one example:

A list of patients, with their [`managingOrganization`](https://hl7.org/fhir/patient-definitions.html#Patient.managingOrganization) and [`generalPractitioner`](https://hl7.org/fhir/patient-definitions.html#Patient.generalPractitioner) in the same table.

Right now, we have to issue 3 HTTP requests: one for the list of patient, one for the referenced Organizations, and one for the referenced Practitioner.

We know that we could use GraphQL for this, but the GraphQL endpoint has other shortcomings: no mutations (so now we have 2 client caches to manage), and no support for pagination that we could find.

**Comment by rahul1** [comment]
Some of our customers could benefit from this in places where they are currently using graphQL. Some specific examples from the field:

- Querying RelatedPersons and Patients related to a specific patient
- Querying ActivityDefinitions and ObservationDefinitions associated with a PlanDefinition
