### ISSUE TITLE
Research replacing enum with union types

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1303]
[Reference link](https://dev.to/dvddpl/whats-the-problem-with-typescript-enums-2okj)

**Comment by mattwiller** [comment]
I read through some of the TypeScript documentation about enums and union types; and had a few main takeaways.  Consider for example an existing enum like [this one](https://github.com/medplum/medplum/blob/9aeeffa461d858def6e693079b84bf6178e49804/packages/core/src/search/search.ts#L37) from the core search code:
```ts
export enum Operator {
  EQUALS = 'eq',
  // ...
}
```
- Enums compile to an object mapping enum names to values, union types compile down to value literals
    - e.g. `Operator.EQUALS` vs. `'eq' as Operator`
- Both options only appear to support numeric or string values, so we couldn't use e.g. [`Symbol`][symbol] to represent the enum values in order to avoid string equality checks

I also did a few quick microbenchmarks and wasn't able to discern any real performance impact of using one or the other.

Based on this, I'm not sure if there's much value in switching the current uses of enums with union types.  I personally think it's pretty useful having the full set of enum values live in an exported object for most use cases, through there may be a few places where the union types make more sense.

[symbol]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**Comment by codyebberson** [comment]
@mattwiller  - Thanks for feedback.  

This is an ancient ticket, so no strongly held opinions here.

I think the main motivation is that TypeScript `enum`s have a small degree of code bloat in JavaScript output:

https://www.typescriptlang.org/play?#code/KYOwrgtgBA8gDsATgQwC4HtEEYoG8BQUUAogIoCqAggDIDKUAvFAOTACOzANIVAHIwAVAPpkqdRixDAu+AL758qAJ4JYCFBkQAmCaw5QAPpOkBufEA

<img width="960" alt="image" src="https://user-images.githubusercontent.com/749094/233699871-f4ce70c8-325a-4011-9a86-7631a8ecc806.png">

With that said, I think I largely agree with you, that there isn't much value in switching.
