### ISSUE TITLE
Enable Okta authentication via OpenID

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#1381]
The basics of "auth with Okta" are straightforward.  The challenge here will be weaving it into the current auth flow, which is quite complex.

In a perfect world, we could add Okta simply as another auth provider at the beginning of the flow:

![image](https://user-images.githubusercontent.com/749094/211216216-1dccd7c3-b23c-4b0f-a793-fee2eb1d5fd1.png)

Unfortunately, Okta partitions auth endpoints by customer, so there is no global auth endpoint.  Instead, you need to know the domain by customer.

Options:
1. Global rule by email address
  a. For example, first ask for email.  If the email address ends with "@example.com" then redirect to the Okta auth page configured for "example.com".  This is what Box does.
  b. This is probably the simplest and least intrusive option.
  c. Important distinction between "global user" and "project user".  By default, we configure most users as "global users", meaning that they can be members of multiple projects.  For open patient registration, we use "project user", which means that the user account is isolated to the project.  We should only apply this global Okta rule to global users, and not project users.
2. Ask for project at top of sign-in
  a. For example, ask for a project ID or a project alias as the first field in the sign-in page. This is what the AWS console does.
  b. This would simplify things for Medplum engineering, but it's a pretty bad experience for users, because now they need to remember another piece of information.  Even if we make it easy to use friendly alias names like "foo", it will be confusing and will probably increase support tickets.

**Comment by reshmakh** [comment]
This is a hard one - as there aren't really any good options that you need to know a lot alot about a user in order to choose the right authentication method - but we are authenticating them because we don't know who they are.  

Both options are viable, but there are drawbacks to each.  Our multi-project UI is another good experience that would be hampered by this as well.  

It does seem like Option 1 is preferable to Option 2 as we it is least intrusive, and represents the spirit of what customers want.  

We need to improve the error message for developers who are using the register and sign in react components to ensure that they are passing in project Ids to streamline the login for end users.  

Question: this will force Okta login for customers with linked emails if they are developing on localhost right?  Will Okta allow that?

**Comment by codyebberson** [comment]
> Question: this will force Okta login for customers with linked emails if they are developing on localhost right? Will Okta allow that?

Oo.  Good catch.  Not only localhost, but all separate front-ends.

**Comment by rahul1** [comment]
Just chiming in here, it does seem like option 1 is preferrable if we can make it work. We have a lot of name collisions for Project names, so creating some kind of alias system for them would be difficult at a practical level as well.

**Comment by reshmakh** [comment]
Closing this out with related PRs as follows:

https://github.com/medplum/medplum/pull/1394
