### ISSUE TITLE
`MedplumClient.signInWithRedirect()` does not set the scope parameter

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1388]
Medplum's /oauth2/authorize endpoint requires the `scope` variable to be set to `"openid"`. However, right now the medplum client library's [`signInWithRedirect`](https://github.com/medplum/medplum/blob/main/packages/core/src/client.ts#L1966-L1977) method doesn't set this parameter.

**Comment by opiation** [comment]
Thanks for filing this ticket @rahul1 from our [discussion on Discord](https://discordapp.com/channels/905144809105260605/1062802755053436958/1062851241077653635)! I appreciate the fast response. Since I had to do some of the research to report the issue, here are my findings:

The place where the `scope` parameter is expected in `authorize.ts`:
https://github.com/medplum/medplum/blob/5860113cbe9ff67e2aa5acd21b326a09fa884902/packages/server/src/oauth/authorize.ts#L66-L70

The place where the redirect happens without setting the `scope` param (ostensibly to `"openid"`):
https://github.com/medplum/medplum/blob/5860113cbe9ff67e2aa5acd21b326a09fa884902/packages/core/src/client.ts#L1966-L1977

Seems like a quick fix might be to add the following in `requestAuthorization` somewhere before the redirect with `window.location.assign(...`:

```ts
url.searchParams.set("scope", "openid");
```

I took a quick look at the relevant `client.test.ts` but the `openid` scope requirement doesn't seem to be tested here at all, unless I'm missing something.
https://github.com/medplum/medplum/blob/5860113cbe9ff67e2aa5acd21b326a09fa884902/packages/core/src/client.test.ts#L310

I'm not sure what @codyebberson thinks of this but I might recommend spying on `window.location.assign` and validating that its received argument is a valid URL string with the expected params. Roughly something like this:

```ts
global.window = Object.create(window);
const locationAssignment = jest.fn();
Object.defineProperty(window, 'location', {
  value: {
    assign: locationAssignment,
  },
  writable: true,
});

await client.signInWithRedirect();
expect(locationAssignment).toHaveBeenCalled();
const redirectParams = new URL(locationAssignment.mock.lastCall[0]).searchParams;
expect(redirectParams.get("code")).toEqual(expect.stringMatching(regexForCode))
expect(redirectParams.get("scope")).toEqual("openid")
// more param testing
```

Hope this helps :handshake:!

**Comment by opiation** [comment]
For what it's worth, I found a small workaround that works _enough_. I noticed that the redirect built by the `MedplumClient` uses the `authorizeUrl` to do so:

```ts
const url = new URL(this.#authorizeUrl); 
```

Thus, I can inject the `scope` param by specifying the `authorizeUrl` manually:

```ts
new MedplumClient({
  authorizeUrl: "localhost:8000/oauth2/authorize?scope=openid",
  baseUrl: "localhost:8000/"
})
```

Now, the request is accepted by the Medplum server but I encounter another _seemingly_ unrelated issue. The server responds by redirecting me to my `redirect_uri` but with `/oauth` appended with all the query params sent with the initial `/oauth/authorize?...` sign-in redirect.

Let me know if the above is a separate issue that should be filed separately on GitHub or if I'm doing something silly.

**Comment by rahul1** [comment]
@opiation Thank's so much for the detailed follow-up. We'll fix the underlying issue first, and then see if a follow up ticket is needed. We might end up resolving your 2nd issue in the course of fixing the 1st!

**Comment by rahul1** [comment]
@opiation One clarifying question - 
My understanding is that you are trying to use Medplum as your identity provider, not a 3rd party auth provider. 

As I understand it: 
- You have a  standalone react app
- You're redirecting to [api.medplum.com/oauth2/authorize](http://api.medplum.com/oauth2/authorize) 
- You want and they want to login at [https://app.medplum.com/oauth](https://app.medplum.com/oauth)

Is that right?

**Comment by opiation** [comment]
> Is that right?

Yes, though I'm not currently using your hosted Medplum instance, but my own local instance. The Medplum app is exposed at `localhost:3000` and the Medplum server at `localhost:8103`. I assume that would mean:
* I have a standalone React app
* I'm redirecting to `http://localhost:8103/oauth2/authorize`
* I want and they want to login at `http://localhost:3000/signin` <-- `/signin` seems to be the login page for the app

**Comment by codyebberson** [comment]
@opiation - Thanks for filing.  Once upon a time, `scope` was not a required param, and it looks like `signInWithRedirect` somehow fell through the cracks.  Good bug, thank you!
