### ISSUE TITLE
Adding aud parameter for authorize request gives error message

### ISSUE THREAD

**Issue by yurycodex** [medplum/medplum#1432]
Request authorize endpoint with adding aud parameter
https://api.medplum.com/oauth2/authorize?aud=https%3A%2F%2Fapi.medplum.com&client_id=992cb882-7e65-4385-aef6-36b7cd9d7b92&redirect_uri=https%3A%2F%2Fpatient-ehr.codexhealth.com&response_type=code&scope=openid&state=2023-01-09T15%3A27%3A25-08%3A00 

it backs with `invalid_request` error message
https://patient-ehr.codexhealth.com/v0/sso?redirectpath=/&redirectparams=error=invalid_request&state=2023-01-09T15%3A20%3A07-08%3A00

aud is required parameter now: https://build.fhir.org/ig/HL7/smart-app-launch/app-launch.html#step-4-authorization-code

**Comment by codyebberson** [comment]
@yurycodex Thanks for filing.

Two separate questions:

1. Yes, you're right, it looks like the `aud` parameter should be required, and it is currently optional.  We can fix that.
2. The only accepted value right now is the FHIR base URL, for example "https://api.medplum.com/fhir/R4" for our production environment.  If I remember correctly, that was the value required by the [Inferno compliance suite](https://inferno.healthit.gov/). We can research if other base URL's are allowed (i.e., "https://api.medplum.com" instead of "https://api.medplum.com/fhir/R4")

As a short term fix, can you try to use "https://api.medplum.com/fhir/R4" as your `aud` parameter?

(cc @rahul1)

**Comment by yurycodex** [comment]
https://api.medplum.com/fhir/R4/oauth2/authorize?aud=https%3A%2F%2Fapi.medplum.com&client_id=992cb882-7e65-4385-aef6-36b7cd9d7b92&redirect_uri=https%3A%2F%2Fpatient-ehr.codexhealth.com&response_type=code&scope=openid&state=2023-01-30%3A27%3A25-08%3A00

returns for me:
{"resourceType":"OperationOutcome","id":"unauthorized","issue":[{"severity":"error","code":"login","details":{"text":"Unauthorized"}}]}

@codyebberson

**Comment by codyebberson** [comment]
@yurycodex Sorry, I was unclear in my answer.  The "fhir/R4" goes in the `aud` parameter.  Could you try this URL?

https://api.medplum.com/oauth2/authorize?aud=https%3A%2F%2Fapi.medplum.com%2Ffhir%2FR4&client_id=992cb882-7e65-4385-aef6-36b7cd9d7b92&redirect_uri=https%3A%2F%2Fpatient-ehr.codexhealth.com&response_type=code&scope=openid&state=2023-01-30%3A27%3A25-08%3A00
