### ISSUE TITLE
Add access policy variable for "%account"

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1441]
Right now, the `compartment` property of our access policies allow:

- A fixed value (e.g. for an Organization)
- The `%patient` or `%profile` variable (synonymous)

This issue is a request to add a new variable, `%account`, that would write whatever is in the current user profile's `meta.account field` to the resource's account. 

Combined with #1440  this will give us a lot more flexibility on crafting access policies.

**Comment by codyebberson** [comment]
@rahul1 One clarifying question:  Any thoughts on what the value of `%account` should be when there is no `meta.account`?

Option 1 - nothing, but that could lead to invalid reference errors

Option 2 - some default fallback ID?

Also regarding this: 

> The %patient or %profile variable (synonymous)

The intent was to deprecate `%patient`, and remove it from the system entirely.

I would like to either continue with that plan, or to justify keeping it.  For example, it could be that `%patient` is the same as `%profile` when the profile resource is a `Patient`, but is `undefined` or an error otherwise?

**Comment by codyebberson** [comment]
@rahul1 Is this obsolete with the new plan in https://github.com/medplum/medplum/discussions/1453 and https://github.com/medplum/medplum/pull/1520 ?

**Comment by rahul1** [comment]
@codyebberson Yeah I think we can close this for now and open a new ticket if a use case arises
