### ISSUE TITLE
Document patient de-duplication patterns

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1460]

**Comment by reshmakh** [comment]
[Internal documentation](https://docs.google.com/document/d/1uRLtwW7L6CpJrH-TDojPDjRrDYTcbeEbymZ4umrbwWI/edit#heading=h.rxun6kfyt6yc)

**Comment by bearjaws** [comment]
Definitely a lot of patterns that range from most robust to least. For most purposes, we will assume we do not have a SSN or health card # since those are 100% matches when combined with Country / Province. This has been my general experience. 

1. Exact, First name, last name, DOB, ZIP / Postal code (this is 99.999% chance to be a duplicate, but there are names where its possible)
2. Phonetic first name, last name, dob, zip code (~95%, with better matching for human error)
3 Phonetic first name, last name (gender dependent, last name can change for women), dob (prevents false negatives due to marriage)

Generally the flow goes:

1. Add or update patient
2. Generate hashes of the patient information above (on update only update if one of demographics is impacted)
3. Store hashes in many to one table
4. If a match is found when a user is adding or updating a patient, present the option to merge.
5. When navigating to an existing patient record in UI, if a new match is found (need a table to track ignored matches historically), present a notification to merge potentially matching patients.
6. Merge should be as non-destructive as possible, people make mistakes and sometimes you need to undo merges.
7. As many attributes as possible should be migrated to the net new patient. This can be tricky for items like documentation (make new file or update pointers to existing? Multiple patients sharing the same file?)

Hope this is helpful and let me know any questions you have!

**Comment by rahul1** [comment]
Thank you so much @bearjaws ! We'll try to incorporate these learnings into our docs - we appreciate your contributions

**Comment by rahul1** [comment]
@bearjaws do you have a recommendation for phonetic comparison of names?

**Comment by reshmakh** [comment]
Sample bot https://github.com/medplum/medplum-demo-bots/pull/52

**Comment by reshmakh** [comment]
Pre-release documents, in preparation for publication:
1) [De-duplication diagrams](https://docs.google.com/presentation/d/1Rqp3dOEGoMeWKuqVqpv3FrO2I3DmritXqW2EPq0-iu0/edit#slide=id.g20ff99647a4_0_285)
2) De duplication design notes [document](https://docs.google.com/document/d/1uRLtwW7L6CpJrH-TDojPDjRrDYTcbeEbymZ4umrbwWI/edit#heading=h.98yw6wzah51f)

**Comment by reshmakh** [comment]
Related [Blog Post](https://www.medplum.com/blog/patient-deduplication)

**Comment by rahul1** [comment]
Fixed by #1696
