### ISSUE TITLE
readResource promise never resolves when autoBatchTime set and resource does not exist

### ISSUE THREAD

**Issue by natemerrill** [medplum/medplum#1793]
When autoBatchTime is set, the promise returned by readResource never resolves when trying to read a nonexistent resource. If I don't use autoBatchTime, it works fine and the `catch` and `finally` blocks handle the error like normal.

**Comment by codyebberson** [comment]
Hi @natemerrill - What version of `@medplum/core` are you using?  There was a bug a few versions back where some errors did not correctly `reject` the Promise. (see https://github.com/medplum/medplum/pull/1507 fixed in version 2.0.3).

If you see this behavior in 2.0.3+, then we'd be happy to dig in.

**Comment by natemerrill** [comment]
I'm on 2.0.12. Looks like you've already got something pushed though,
thanks!
