### ISSUE TITLE
No options on "Choose profile" page

### ISSUE THREAD

**Issue by kmiwa007** [medplum/medplum#1825]
There seems to be an issue w/ the demo provider app which was also seen running locally.  On this page there's no option to select which Project and can't get past login screen.  I think it gets stuck here because I have access to 2 projects.

<img width="1114" alt="Screen Shot 2023-04-13 at 3 33 54 PM" src="https://user-images.githubusercontent.com/110495168/231897598-053b80e7-811a-42ea-96a3-05ea3809be3c.png">

**Comment by reshmakh** [comment]
This usually happens because a Practioner or Patient resource attached to the ProjectMembership was accidentally removed.  [User guide docs](https://www.medplum.com/docs/auth/user-management-guide#creating-memberships).  If you have a project and confirm that you can log in, update the `projectId` on the signin form on your localhost and hopefully you should be good to go. [Instructions](https://github.com/medplum/foomedical-provider#account-setup)

**Comment by kmiwa007** [comment]
Thanks for the reply.  When running the provider app locally, we were able to login on Friday but now seems we get this screen again.  I added the projectId to the SignInForm but still see this empty "Choose profile" screen after logging in.

**Comment by reshmakh** [comment]
@kmiwa007 - did you end up getting this working?
