### ISSUE TITLE
Support for chaining/reverse chaining

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1975]
[Community request](https://discord.com/channels/905144809105260605/905144809105260608/1103322601209737276)

The FHIR spec allows for searching a resource based on the search params _of linked resources_. https://www.hl7.org/fhir/search.html#chaining

For example: 
`GET [base]/DiagnosticReport?subject.name=peter`

Reverse Chaining: 
`GET [base]/Patient?_has:Observation:patient:code=1234-5`

We'd want to make sure we implement this in a way that is performant

**Comment by sshyshspsoft** [comment]
@rahul1 thanks again for bringing up this issue here
The example of a query may be next
`/fhir/R4/Practitioner?active=true&_has:Schedule:actor:_has:Slot:schedule:start=gt2023-05-05T00:00:00.00000&_has:Schedule:actor:_has:Slot:schedule:status=free&_sort=-.name.0.family`

So I want to get all the active practitioners that have available slots from some point in time

**Comment by zeigerpuppy** [comment]
great request, chaining is one of the more powerful FHIR features and makes queries a lot more efficient.
