### ISSUE TITLE
Utility method for checking the type of a reference when that type can combine multiple types

### ISSUE THREAD

**Issue by alexgoto** [medplum/medplum#1984]
Hello Medplum,

When i implement logic of interaction of FHIR resources i often need check type of reference when it can combine multiple types. For example, i need to filter CarePlans where subject is only Patient, not Group. 

I didn't found any suitable method in @medplum/core utils and implement it myself. Perhaps it would be more user frendly if you add this util to @medplum/core which already has resolveId, createReference, getReferenceString and more. 

For example, this method might look like this:

```ts
function checkReferenceType<T extends ResourceType, R extends T>(reference: Reference<ExtractResource<T>>, resourceType: R): boolean {
  return reference.reference.split('/')[0] === resourceType;
}
```

If you think that it could be useful for the project, I can do pull request.

**Comment by codyebberson** [comment]
Hi @alexgoto that would be a welcome addition!

Rather than returning `boolean`, you might consider using a [Type Predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) to assert the resulting type by returning `reference is Reference<ExtractResource<K>>`:

```ts
function checkReferenceType<K extends ResourceType>(reference: Reference, resourceType: K): reference is Reference<ExtractResource<K>> {
  return reference.reference.split('/')[0] === resourceType;
}
```

(untested)
