### ISSUE TITLE
Add "bulk" commands to the Medplum CLI

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2024]
Add "bulk" commands to the Medplum CLI

Use case is to pull data from  https://bcda.cms.gov/guide.html#try-the-api and load it into a Medplum project.

medplum bulk export x where x is a Group/id, a Patient/id or a system level export
medplum bulk import filename.ndjson to import into your current project

You should be able to do this with just the medplum CLI then:

```
# Use BCDA client credentials
export MEDPLUM_CLIENT_ID=$BCDA_CLIENT_ID
export MEDPLUM_CLIENT_SECRET=$BCDA_CLIENT_SECRET
export MEDPLUM_BASE_URL=$BCDA_BASE_URL
medplum bulk export Patient > myfile.ndjson

# Use Medplum client credentials
export MEDPLUM_CLIENT_ID=$MY_CLIENT_ID
export MEDPLUM_CLIENT_SECRET=$MY_CLIENT_SECRET
export MEDPLUM_BASE_URL=https://api.medplum.com/
medplum bulk import myfile.ndjson

# Or use Medplum user login
medplum login
medplum bulk import myfile.ndjson
```

**Comment by codyebberson** [comment]
`medplum bulk export Patient > myfile.ndjson`

would translate to:

```bash
curl -X GET 'https://sandbox.bcda.cms.gov/api/v1/Patient/$export' \
-H "accept: application/fhir+json" \
-H "Prefer: respond-async" \
-H "Authorization: Bearer {access_token}" \
-v
```

And then polling the status endpoint until it is done.

**Comment by codyebberson** [comment]
Sorry to add scope creep, but a few extra requirements emerged.

We need to support this in all 3 of the following cases:
1. In `MedplumClient`, from any app
2. In Medplum Bots (which use `MedplumClient`, so hopefully this is automatic)
3. In the CLI (which also uses `MedplumClient`)

The `MedplumClient` call should probably be something like:

```ts
bulkExport(resource: string): Promise<Partial<BulkDataExport>>
```

It should:
1. Initiate the bulk export
2. Get the `Content-Location` for status
3. Poll the status URL until the job is complete
4. Return the `BulkDataExport` details

The Medplum Bot case will be a matter of calling `bulkExport()`.  The problem is that Bots have a default timeout of 10 seconds, which will not be enough for any serious usage.  We can flag that as a separate issue for further discussion later (i.e., we have super admin tools that can increase timeout one-off).

The Medplum CLI case should call `bulkExport()`, wait for the results, and then download the `BulkDataExport.output` URLs to the local file system.

**Comment by tonylee80** [comment]
> Sorry to add scope creep, but a few extra requirements emerged.
> 
> We need to support this in all 3 of the following cases:
> 
> 1. In `MedplumClient`, from any app
> 2. In Medplum Bots (which use `MedplumClient`, so hopefully this is automatic)
> 3. In the CLI (which also uses `MedplumClient`)
> 
> The `MedplumClient` call should probably be something like:
> 
> ```ts
> bulkExport(resource: string): Promise<Partial<BulkDataExport>>
> ```
> 
> It should:
> 
> 1. Initiate the bulk export
> 2. Get the `Content-Location` for status
> 3. Poll the status URL until the job is complete
> 4. Return the `BulkDataExport` details
> 
> The Medplum Bot case will be a matter of calling `bulkExport()`. The problem is that Bots have a default timeout of 10 seconds, which will not be enough for any serious usage. We can flag that as a separate issue for further discussion later (i.e., we have super admin tools that can increase timeout one-off).
> 
> The Medplum CLI case should call `bulkExport()`, wait for the results, and then download the `BulkDataExport.output` URLs to the local file system.

I've created a separate issue #2074  for the changes needed for Medplum client
