### ISSUE TITLE
Cannot add multiple project "features" using the react component

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2454]
Repro: 
- Enable bots on a Project using the "Edit" tab
- Save
- Go back to the Edit tab
- add "email" to the list of features
- Click "Save"
- Navigate to the JSON tab of the project

The features only contains "bots", not "email"

**Comment by codyebberson** [comment]
Clarification: it is possible, the UI is just bad.

Reasons it is bad / How to work around it

1. The input is a `<MultiSelect>`, so you can put your cursor in the same box.  Don't do that.  Instead, click the green "+" plus icon on the right:

![image](https://github.com/medplum/medplum/assets/749094/3d680871-bdd6-48a4-ae89-0c68a5659462)

2. We don't currently have a `ValueSet` for the features list, so there are no autocomplete values.  Instead, you have to manually click the "+ Create: email" menu option

![image](https://github.com/medplum/medplum/assets/749094/885fcba0-fd7f-4810-b555-9e9fc294c87a)

3. If you don't click the "Create" menu option, you get into this bad state.  If you hit "Save" like this, it will not persist the new value:

![image](https://github.com/medplum/medplum/assets/749094/d1368865-4685-4fb6-8ab1-9273330f8ec1)

![image](https://github.com/medplum/medplum/assets/749094/7e593517-1b68-48e8-83c2-140006b0ae63)


Ideal fixes:
1. The input should not be a `<MultiSelect>`
2. We should have a `ValueSet` for the list of available features
3. The UI should be more clear about an enum value in a bad state

As an example of the 3rd fix, here's what happens if you try to enter an invalid email address in the Gmail compose window:

<img width="461" alt="image" src="https://github.com/medplum/medplum/assets/749094/cfc33e50-0114-4870-a778-9eebdb7a50cb">

**Comment by rahul1** [comment]
Thanks for the explanation. How would you feel about a quick fix of setting `maxSelectedValues` to 1? Then we wouldn't have to have a globally available ValueSet. 

This is an input that only super admins can see anyway, so might be sufficient

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2525
