### ISSUE TITLE
Support Email Verification Link

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2515]
User Driven - https://discord.com/channels/905144809105260605/1131849169095639084/1131849169095639084

Our user has cloned foo medical and successfully set up the invite process. They would now like to add an email verification link to the welcome email the patient receives. While we do currently support [custom welcome emails](https://www.medplum.com/docs/auth/custom-welcome-emails), I don't think we have all the functionality to implement this via Bots. 

Some thoughts on implementation: 
- Allow bots to be executed by GET requests. Then users can create custom emails with a link to an email verification Bot
- Support this a native part of the `/newuser` flow somehow?

**Comment by ashokgit** [comment]
Following

**Comment by codyebberson** [comment]
> Allow bots to be executed by GET requests. Then users can create custom emails with a link to an email verification Bot

This exists: https://github.com/medplum/medplum/pull/2245

> Support this a native part of the /newuser flow somehow?

Yeah, we've discussed this in the past.  One idea was to add a `Project` setting for `newUserBot`.  If set, we invoke the Bot, and let the Bot handle all of the welcome email work.  If not set, fall back to current behavior.

**Comment by mattlong** [comment]
@rahul1 @codyebberson Here's my proposed solution:

Add and optional `Project.newUserBot`. When the bot is specified, automatically invoke (i.e. without a `Subscription` needing to exist) the bot whenever a `ProjectMembership` is created. Or, should the bot be more specifically targeted at new patient users, e.g. only be invoked in `newPatientHandler`? What should happen if the bot fails to execute successfully?

Depending on whether the bot is only targeted at new patient users or at all new users, the existence of `Project.newUserBot` may need to disable/override (or perhaps makes it opt-in instead of opt-out?) the `sendEmail` parameter of `/:projectId/invite`.
