### ISSUE TITLE
Batch upload tool doesn't handle multiple files

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2570]
User Driven: https://discord.com/channels/905144809105260605/1134531308962467851/1134547021689274458

Right now our batch upload tool tells users to "Upload as many files as you like". But the app only processes the [first file that is uploaded.](https://github.com/medplum/medplum/blob/9d952bb739ce5b6314ffaf2d0fa68f0aca98cd07/packages/app/src/BatchPage.tsx#L56) 

Two options here: 
1. Change the copy on the Batch upload tool (easy)
2. Modify the Batch upload tool to process multiple files

**Comment by Abi-Liu** [comment]
Hey can I take this issue if no one's working on?

**Comment by codyebberson** [comment]
@Abi-Liu - Yep! 

I agree with @rahul1 that we should start with the simple fix of "Change the copy on the Batch upload tool (easy)"

If you're feeling ambitious, we could try to support multiple uploads.  That's really 2 subtasks:

1. In the `handleFiles` function in [BatchPage.tsx](https://github.com/medplum/medplum/blob/9d952bb739ce5b6314ffaf2d0fa68f0aca98cd07/packages/app/src/BatchPage.tsx#L56) process all files rather than `files[0]` (easy)
2. Figure out how to show the results of multiple uploaded files...  @rahul1 do you have any thoughts on what that should look like?
    a. Keep appending output to the same panel (easiest)
    b. Add output tabs for each file (medium)
    c. Full on UI for showing each uploaded file, upload state, and results (hardest)

**Comment by Abi-Liu** [comment]
@codyebberson  Hey just wanted to make sure that I'm clear on everything.

For number 1 I could just do something like a for loop to iterate through and have ```reader.readAsText(files[i])``` or something like that right?

As for number 2, To just append all of the outputs to the same panel I could just map each item in the output array to the JSX element responsible for showing the output.

Am I missing anything?

**Comment by rahul1** [comment]
@Abi-Liu I think that's the right direction. 

For #2, if you could somehow show which file produced which output, that would be nice for helping users debug

**Comment by codyebberson** [comment]
Hi @Abi-Liu  - Yep, that all sounds great!

**Comment by Abi-Liu** [comment]
Sounds good! I'll get started on the fix. Are there any files I can use for testing, or can I just use any pdf file?

**Comment by rahul1** [comment]
Hi @Abi-Liu - the target files for this tool are JSON files that contain FHIR Bundle resources. 

We have two examples on our docs page: https://www.medplum.com/docs/tutorials/importing-sample-data
- https://drive.google.com/file/d/1bEyKSy55k9ZrrDLBj1NkHyL4ou75_eRX/view?usp=sharing
- https://drive.google.com/file/d/1Zj3EWeWj7-wP52CAZjSqzwCxZMlx6QZM/view?usp=share_link

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2614 - thanks @Abi-Liu !
