### ISSUE TITLE
"operation" input doesn't appear upon opening "filters" dialog

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2618]
## Repro
1. Navigate to https://app.medplum.com/Patient
2. Click "Filters"

By default, "Field" is set to "Id". However, there is no input for "operation'

<img width="889" alt="image" src="https://github.com/medplum/medplum/assets/1259236/417c4171-4dfe-44a9-b51d-3924cb2aa7b9">

However, after doing this: 
1. Set "Field" to Last Updated
2. Set "Field" back to "Id"

The "operation" input now appears.

<img width="884" alt="image" src="https://github.com/medplum/medplum/assets/1259236/6ba06c90-73cb-4977-9324-58a001550833">

**Comment by abhinaisai2002** [comment]
Hey Can you describe more about this issue??

**Comment by abhinaisai2002** [comment]
Hey i ran the code locally, when opening the filters tab the fields are not showing, what to do on this?

**Comment by codyebberson** [comment]
Hi @abhinaisai2002 -

The bug is that the "Field" input defaults to the first value, but the "Operation" input only appears after a "change" event.

The quick fix here is to add a blank/empty option in the field selector.

The fix will be here in `SearchFilterEditor.tsx`:  https://github.com/medplum/medplum/blob/main/packages/react/src/SearchFilterEditor/SearchFilterEditor.tsx#L174-L179

The `data` prop should include an empty value, something like this:

```tsx
 data={['', ...Object.keys(props.searchParams).map((param) => ({ value: param, label: buildFieldNameString(param) }))]}
```

(untested)

> Hey i ran the code locally, when opening the filters tab the fields are not showing, what to do on this?

If your fields are not loaded correctly, it likely means that your schema is not correctly loaded.  You should be able to fix that using "Rebuild Structure Definitions" in the super admin panel.  See here: https://www.medplum.com/docs/self-hosting/super-admin-guide#rebuild-resources

**Comment by abhinaisai2002** [comment]
Ok, i will be working on this issue?

**Comment by abhinaisai2002** [comment]
Hey I sent the pr and it is working fine, but the build is failing. Can you help me in that I am not able to understand that

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2645

Thanks @abhinaisai2002 !
