### ISSUE TITLE
CDK Params not written to param store

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2727]
In our [self-hosting docs](https://www.medplum.com/docs/self-hosting/config-settings), we note a few params that are setup by CDK deploy:
- `signingKeyId`
- `botLambdaRoleArn`
- `database`
- `redis`

However, when validating against some of our demo deployments, these are not currently being set by our CDK code.

**Comment by codyebberson** [comment]
`signingKeyId` is currently broken.  Good bug.  It looks like it was originally set, but then there was a regression when we added support for regions other than `us-east-1`.

One major CDK limitation is that all "resources" must be within the same AWS region.  Some resources must be in `us-east-` (i.e., CloudFront distributions).  The way we handle that is by creating 2 "stacks".  That creates an unfortunate situation for `signingKeyId`, because it is created in `us-east-1`, but the Parameter Store entry must be created in the primary region (which may or may not be `us-east-1`).

For that, I'm inclined to move the `signingKeyId` logic out of CDK and into the Medplum CLI `aws init` command, similar to how we pre-create SSL certificates.

Alternatively, the servers could look for config settings from multiple regions at startup, but that feels less clean.

--------

`botLambdaRoleArn` is set explicitly: https://github.com/medplum/medplum/blob/main/packages/cdk/src/backend.ts#L422-L427

--------

`database` and `redis` are documentation issues.  Our CDK code writes parameters for `DatabaseSecrets` and `RedisSecrets`, which are IDs for AWS Secrets Manager.  Our config loader understands that, recognizes `DatabaseSecrets`/`RedisSecrets`, and loads the appropriate values from AWS Secrets Manager.  For better or worse, CDK only supports exposing database credentials via AWS Secrets Manager, so we have to do it this way.

**Comment by codyebberson** [comment]
https://github.com/medplum/medplum/pull/2728
