### ISSUE TITLE
Adding "Coding" to Questionnaire open-choice question type will not save

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2991]
Repro steps:

1. Create a new questionnaire
2. Add a question with type Open Choice
3. Add one of the choices of type "Coding" and hit save

Expected: questionnaire will save
Actual: Error - malformed questionnaire resource

Screencap: https://share.descript.com/view/WIAwqo4RJ9R

**Comment by Mogoww** [comment]
Hello,

I would like, if possible, to examine your issue in order to contribute to this project. I encountered an error when following the steps described in the reproduction. Instead of the "malformed questionnaire resource" error mentioned in the original issue, I received a different error message that said: "Something went wrong: Unable to read properties of an undefined value (reading 'value')." Is the error still present on your end?
