### ISSUE TITLE
Consider using drizzle or prisma

### ISSUE THREAD

**Issue by masterbater** [medplum/medplum#3176]
So I like the developer experience of these two orm and very easy to be familiar. Do you have any plans to rewrite the source code using one of these two? or you will still use node-posgres going forward?

**Comment by codyebberson** [comment]
For the foreseeable future, we will stick with node-postgres.

The FHIR search implementation has very particular requirements at the SQL layer.  We tried Prisma in early prototypes (early 2021), but quickly ran into ORM [object–relational impedance mismatch](https://en.wikipedia.org/wiki/Object%E2%80%93relational_impedance_mismatch) issues.  We tried Knex.js for a while as well, but ran into limitations with TypeScript type definitions.  We have been quite content with our current data access layer for a while now.

We have long term aspirations for a plugin model so that users could bring their own implementation of the data layer.  For example, you could write an implementation of [`FhirRepository`](https://github.com/medplum/medplum/blob/main/packages/fhir-router/src/repo.ts) using DynamoDB or CosmosDB or BigTable.  I think that would be an appropriate time to explore ORM alternates.  Here is that discussion: https://github.com/medplum/medplum/discussions/1424
