### ISSUE TITLE
Enhancement for Project-Specific Password Reset

### ISSUE THREAD

**Issue by ravindra-tc** [medplum/medplum#3340]
**Background**
We addressed a limitation in the password reset functionality within the Medplum system. The current process lacks project specificity, making it challenging to determine the intended project when resetting the password for a user associated with multiple projects.

**Issue Details:**

1. **Problem Statement:**
   - The password reset process in Medplum is not project-specific, causing difficulties when attempting to reset the password for a user associated with multiple projects.

2. **Global User Consideration:**
   - Exploring the option of creating a global user to cover all projects was discussed. However, the current system constraints, specifically the requirement for a project ID during user creation, make this approach unfeasible.

3. **Feasibility of Project-Specific:**
   - The objective is to enhance the password reset functionality to be project-specific, allowing for a more targeted and accurate process when dealing with users across multiple projects.

**Proposed Resolution:**
   - Implement a project-specific password reset mechanism, ensuring that the system can correctly identify and process password resets for users associated with multiple projects.

**Benefits:**
- Improved security and specificity in the password reset process.
- Enhanced user experience for administrators dealing with users across different projects.

**Comment by rahul1** [comment]
From discord: https://github.com/medplum/medplum/blob/main/packages/server/src/auth/resetpassword.ts#L60-L69


The bug is centered in [these lines](https://github.com/medplum/medplum/blob/ab33abfba36b640aa372e59eb4a58d615fce91e0/packages/server/src/auth/resetpassword.ts#L60-L69). 

The system repo searches for a user by email address. If we have a two project-scoped users in two different projects that share an email address, this search doesn't guarantee returning the correct user
