### ISSUE TITLE
Array-aware validation outcome expressions

### ISSUE THREAD

**Issue by mattlong** [medplum/medplum#3447]
The expressions produced during validation should be specific to the array indices that have issues.

Consider the scenario where `Patient.identifier.system` is required and more than one identifiers exist; some of which have `identifier.system` specified . Since only an expression for `Patient.identifier.system` is included in the outcome, the options are to either highlight all system inputs or disable error highlighting on array inputs:

<img width="501" alt="Screenshot 2023-11-28 at 11 37 38 AM" src="https://github.com/medplum/medplum/assets/933303/2a627d71-6011-4ce0-9e18-159b8368f785">

<img width="744" alt="Screenshot 2023-11-28 at 11 37 15 AM" src="https://github.com/medplum/medplum/assets/933303/b00a561c-1f9e-41ab-9833-aa96660af3f3">

Ideally, the expression returned from validation in the above scenario would instead be `Patient.identifier[1].system`. Assuming that were available, on the frontend, `ResourceArrayInput` would need to pass on the array index a child element input is at and `getErrorsForInput` would need to take that index (if applicable) as a parameter.

**Comment by dillonstreator** [comment]
Just ran into this as well with the attempt to create a Communication resource:
```
Uncaught (in promise) Error: String must contain non-whitespace content (Communication.note.text)
```

This threw me off a bit while troubleshooting so agree there is room to improve DX and UX with error reporting.

**Comment by jogeshwar01** [comment]
@mattlong 
I explored this issue for some time. For the backend, we will need to make all the functions in [validation.ts](https://github.com/medplum/medplum/blob/main/packages/core/src/typeschema/validation.ts) to support arrays and give the errors including index.

The frontend part here seems a bit tricky. For our text inputs, we have used the Input.Wrapper in FormSection component in order to support the error messages.
We have wrapped our ResourcePropertyInput inside FormSection for this.
https://github.com/jogeshwar01/medplum/blob/3111f160fd7bd325948c981de58d6c18a9526d29/packages/react/src/BackboneElementInput/BackboneElementInput.tsx#L76-L92

Now the issue is that this FormSection is defined to support a single input and hence has general prop values. But in case of arrays, the ResourcePropertyInput is going to render more than one input all inside a single Input.Wrapper with same props.
This complicates this a bit. For an array, we won't be able to modify the Input error based upon index.

We may need to move the FormSection inside each of our individual inputs. We can also try to add another Input.Wrapper around the ResourceArrayInput but I am unsure how/if nesting would work.

Also, just wanted to highlight this from the mantine/core docs.
![image](https://github.com/medplum/medplum/assets/85165953/5e2c7609-04b4-479e-8437-efb63d750acd)
