### ISSUE TITLE
New schema diff view does not work with Extension values

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#3469]
We added a new resource diff view in https://github.com/medplum/medplum/pull/3387

Overall, it has been a big improvement, especially on big resources.

Unfortunately, there are a few cases that trigger exceptions and the `<ErrorBoundary>` view.

One reproducible example is Extension values

![image](https://github.com/medplum/medplum/assets/749094/d09f4023-663d-4c3b-b06f-426de8a5a838)

**Comment by jogeshwar01** [comment]
@codyebberson 
Found the bug here. This issue is pertains to all the types with the [x] in their schemas.
The error comes out of the crawlSearchParameterDetails function in details.ts that in turn calls getElementDefinition function.

https://github.com/medplum/medplum/blob/4b3998f494c17baab69a2240d2eed2e326c18295/packages/core/src/search/details.ts#L121-L125

https://github.com/medplum/medplum/blob/4b3998f494c17baab69a2240d2eed2e326c18295/packages/core/src/types.ts#L322-L328

Here, the function expects only the initial part before [x] as the input. But the actual passed one contains the type concatenated with the element. For eg.) Instead of only `value`, we have `valueBoolean/valueDateTime` etc as suggested by the error message as well.

I checked passing in only the values without the type codes here and it does fix this -
![image](https://github.com/medplum/medplum/assets/85165953/a8327402-4fbb-4300-af73-1c1fb3dbdda8)

Now, in the base-schema.json, we have 13 elements that have multiple subtypes (with [x]) including author[x], subject[x], asNeeded[x], amount[x], value[x] and so on.

I think think of 2 options here. Either we can create sort of a map (key value pairs) like valueString : value and so on for all the types and hence the change the propertyName before it goes into getElementDefinition.
Or we can modify the getElementDefinition function itself. For all the multiple type elements, we can check each code one by one.

Rest would like to know what you think of this and we can proceed further from there.

**Comment by codyebberson** [comment]
Hi @jogeshwar01 - Thanks for investigating!  I agree with your analysis.

Adding an extra block in `getElementDefinition()` like this should fix it:

```ts
  for (const element of Object.values(typeSchema.elements)) {
    for (const type of element.type) {
      if (element.path.replace('[x]', capitalize(type.code)) === propertyName) {
        return element;
      }
    }
  }
```


Would you like to take this one?

**Comment by jogeshwar01** [comment]
@codyebberson Yes sure.
