### ISSUE TITLE
Apply fixed/pattern values in ResourceForm

### ISSUE THREAD

**Issue by mattlong** [medplum/medplum#3732]
How should fixed/pattern values be applied to a resource in `ResourceForm`? At a high level, the two most likely approaches would either be:

1. at load time, i.e. as the `ResourceForm` and the tree of input components included in it are setup. 
2. at save time, i.e. when the user clicks OK to save the resource, merge in all fixed/pattern element values into the resource before submitting it to the server to be validated and saved.

The load-time option is preferential since it would allow feedback to the user of which values are fixed and should not (or cannot) be edited so that they don't attempt to fill in values that would only inevitably lead to validation errors. At a high level, the algorithm would be as follows:

* For required array elements (`element.min > 0`), create up to `min` placeholder values
	* For elements with fixed/pattern values within a required element, apply the fixed/pattern value to the placeholder.
* For optional array elements (`element.min === 0`), do NOT create any placeholder values
	* For elements with fixed/pattern values within an optional element, only apply them to existing entries
* When a new array/slice entry is added (i.e. the user clicks the Add button), for both required and optional elements, apply same logic as above.
* For non-array elements, (`element.max === 1`), apply fixed/pattern values, but track that they were applied be default and do not include them in a save request if the user doesn't change anything else in the element.

The application of fixed/pattern values should be centralized rather controlled by individual inputs. The most obvious location is within `ElementContext` since all elements shown in a form are contained within an `ElementContext`. Since applying cardinality & fixed/pattern values requires profile & extensions schemas to be loaded, it must be possible for fixed/pattern values to be applied at various depths within a resource; not just at `ResourceForm` or the top-most `BackboneElementInput`. `ElementContext` also fits nicely with this requirement since a new context is already necessary when a type schema is fetched from the server.

When displaying fixed/pattern elements:
* Display the input in a disabled/read-only state with a tooltip explaining "This value is required by the US Core Patient profile"
* If the resource has an existing value that does NOT conform to the fixed/pattern value, highlight it as an error with a message/question mark icon explaining it does not conform along with a button to set the value to the fixed/pattern value. The guiding principle here is that an existing value should never be changed automatically; the user must explicitly opt-in to the change.

What to do with custom input components that ignore some sub-elements that could have a non-zero `min` or fixed/pattern values? For example, `QuantityInput` shows `value, comparator, unit` but ignores `system, code`. They should mostly just work as if they were hidden form fields. The one exception being when the existing element values that do NOT conform to fixed/pattern values. In that case, a message should be shown for the input similarly as described above: a message is shown for the `QuantityInput` explaining that there the non-conforming values along with a button to set the hidden values to the required fixed/pattern values.

**Comment by codyebberson** [comment]
Thanks @mattlong, lots of good thinking here.  Responses inline:

--------

> 1. at load time, i.e. as the `ResourceForm` and the tree of input components included in it are setup. 

Agree

> 2. at save time, i.e. when the user clicks OK to save the resource, merge in all fixed/pattern element values into the resource before submitting it to the server to be validated and saved.

This will happen on server regardless, but agree that it's less useful in UI.

> * For required array elements (`element.min > 0`), create up to `min` placeholder values
> 	* For elements with fixed/pattern values within a required element, apply the fixed/pattern value to the placeholder.

Makes sense 👍

> * For optional array elements (`element.min === 0`), do NOT create any placeholder values
> 	* For elements with fixed/pattern values within an optional element, only apply them to existing entries

Clarifying question:  the element is "optional", but if an element exists, then it must satisfy the fixed/pattern value?

That makes sense.

> * When a new array/slice entry is added (i.e. the user clicks the Add button), for both required and optional elements, apply same logic as above.

👍 

> * For non-array elements, (`element.max === 1`), apply fixed/pattern values, but track that they were applied be default and do not include them in a save request if the user doesn't change anything else in the element.

🤔 

If `min === 0`, then my assumption would be that we show empty form element.  If `min === 0` and it is fixed value, would the optimal UX be a checkbox?  Because it's effectively there or not?

If `min === 1`, then agree, we should just show the value.  I would assume that we would include it in the submission in that case though.

> The application of fixed/pattern values should be centralized rather controlled by individual inputs. The most obvious location is within `ElementContext` since all elements shown in a form are contained within an `ElementContext`. Since applying cardinality & fixed/pattern values requires profile & extensions schemas to be loaded, it must be possible for fixed/pattern values to be applied at various depths within a resource; not just at `ResourceForm` or the top-most `BackboneElementInput`. `ElementContext` also fits nicely with this requirement since a new context is already necessary when a type schema is fetched from the server.

Makes sense 👍

> When displaying fixed/pattern elements:
> * Display the input in a disabled/read-only state with a tooltip explaining "This value is required by the US Core Patient profile"

👍 

> * If the resource has an existing value that does NOT conform to the fixed/pattern value, highlight it as an error with a message/question mark icon explaining it does not conform along with a button to set the value to the fixed/pattern value. The guiding principle here is that an existing value should never be changed automatically; the user must explicitly opt-in to the change.

That sounds like a good compromise.  It's a tricky situation, but this seems about as good as we can get.

Maybe optimal UI would be a simple button for "fix this", which would swap in the required fixed value.  But that can be future work.

> What to do with custom input components that ignore some sub-elements that could have a non-zero `min` or fixed/pattern values? For example, `QuantityInput` shows `value, comparator, unit` but ignores `system, code`. They should mostly just work as if they were hidden form fields. The one exception being when the existing element values that do NOT conform to fixed/pattern values. In that case, a message should be shown for the input similarly as described above: a message is shown for the `QuantityInput` explaining that there the non-conforming values along with a button to set the hidden values to the required fixed/pattern values. 

These are good questions.  I don't think it's P1 to solve them all, but it's worth thinking about.

One idea we have discussed in the past is updating `<BackboneElementInput>` to support a horizontal/row configuration, such that all of our specialty input components could use that.  There's a lot of complexity in there (when do you use row mode?  do you still show all fields?  what about help text and labels?), but that would probably lead to the "right" solution.

-------

Overall, I think all of these proposals sound good, and definitely on the right track.  Personally, I'm comfortable with some 80/20 thinking here, and we can figure out the long tail edge cases in future revs.
