### ISSUE TITLE
Profile validation fails even when constraint is satisfied

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3753]
User Driven: https://discord.com/channels/905144809105260605/1194887284537954304/1194887284537954304

## Repro
1. Upload the following Structure definition to your project: [test.fhir.json](https://github.com/medplum/medplum/files/13991897/test.fhir.json)

2. Try to save the following encounter: [test-encounter.json](https://github.com/medplum/medplum/files/13991896/test-encounter.json)

## Actual Behavior
Receive the following error: 
![image](https://github.com/medplum/medplum/assets/1259236/22d1bd11-3f5b-48e6-a721-3d106d7b34d6)

## Expected Behavior
The Encounter has a valid identifier that satisfies the constraint, so we would expect to pass

**Comment by codyebberson** [comment]
@mattwiller  - My first instinct would be to test the `identifier.where(a = 'x' and b = 'y')` syntax in the fhirpath project directly

**Comment by codyebberson** [comment]
Putting together a fix now.  There is one issue in our schema validator, and I think perhaps one issue with the user's `StructureDefinition`.

First, in our schema validator, we're not currently validating "root" constraints (i.e., at the top level, on the `Encounter` element definition).  So if you add a root constraint such as `"identifier.where(system='http://example.com' and value='123').exists()"`, it would be ignored.

So, I assume the user may have tried to put that constraint on the `Encounter.identifier` element.  In that case, the constraint expression should omit `"identifier"`, and simply be `"where(system='http://example.com' and value='123').exists()"`, because the context value is the `identifier` array, not the `Encounter`.
