### ISSUE TITLE
Bot.runAsUser has no effect when executed via $execute endpoint

### ISSUE THREAD

**Issue by natemerrill** [medplum/medplum#3906]
As far as I can tell, the `runAsUser` flag only has an effect when the Bot is executed as a result of a subscription. Bots that are executed using the `$execute` endpoint seem to always use the caller's credentials, and any access policy set on the Bot has no effect. Is this intentional, or am I just configuring something incorrectly? It seems out of line with the AccessPolicy strategy described at https://www.medplum.com/docs/bots/consuming-webhooks. Thanks for your help!

**Comment by codyebberson** [comment]
@rahul1  - iirc, we discussed this internally and decided that this is currently "by design".  iirc, the feeling was that `runAsUser=false` on `$execute` would pose a security escalation risk.  We may want to make this a documentation task.

We can revisit after we finish "on behalf of": https://github.com/medplum/medplum/issues/3892

**Comment by natemerrill** [comment]
This was changed in #3919. Sorry that pull request didn't get linked to this issue, should have put the issue number in the description instead of the title.
