### ISSUE TITLE
Polyfill required for running WebSocket Subscriptions on React Native

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4384]
User Driven: https://medplum.slack.com/archives/C06H7LWCA2U/p1712782060890859?thread_ts=1712696521.187989&cid=C06H7LWCA2U

To get the Medplum Websocket subscriptions working on React Native, the user had to add this line to their App root
```js
global.event = require("react-native/Libraries/Events/EventPolyfill").default;
```

We should probably include this in the polyfills we ship

s/o @charlesbthomas for bringing this to our attention!

**Comment by ThatOneBro** [comment]
I found this: https://github.com/facebook/react-native/issues/38004

The recommendation is to not use this particular internal polyfill since it is meant to "be redone later" (TBD how long that will take), but it may be the quick and dirty option and probably is good enough. 

The API is not incredibly complicated anyways so I'm not sure why we shouldn't be able to use that one in our own polyfills 👍
