### ISSUE TITLE
Auto-reconnecting in client when `WebSocket` not intentionally closed

### ISSUE THREAD

**Issue by ThatOneBro** [medplum/medplum#4586]
WebSockets are often flaky under circumstances where connectivity is spotty or inconsistent. We can make working with `WebSocket Subscriptions` and `WebSockets` in general easier for application authors using `MedplumClient` by auto-reconnecting behind the scenes and in the case of `WebSocket Subscriptions` recreating subscriptions with the same criteria automatically if the connection reconnects

**Comment by dillonstreator** [comment]
If a Websocket Subscription is disconnected due to a flaky client connection or a server process exit (expected during deployment or unexpected from an error), gracefully reconnecting in the `MedplumClient` makes a lot of sense.

Given the sensitive/urgent and timely nature of some of the use cases that may call for a Websocket Subscription, in addition to gracefully reconnecting, it would be valuable to enable clients to request a 'replay' of subscription-matching resources between the time of a disconnect->reconnect to ensure clients are not dropping events that could be urgent. I would anticipate this 'replay' to be a default behavior of the `MedplumClient`, if supported by the server.

I couldn't find this concept outlined by the FHIR spec but curious if this something that is on the Medplum teams radar and/or if there's a more appropriate workaround (than what is outlined below) to get the benefits of real-time changes in the client while also having better guarantees of not dropping events?

One workaround is a calling client could listen for a disconnect/reconnect events and query for resources matching the subscription filter between the disconnect period using the `lastUpdated` field, however, this unfortunately wouldn't account for the more complex filtering logic that can be encoded in the subscription extensions.

From a solutioning standpoint, the subscription could be retained after a disconnect and events buffered in redis with a "reasonable" TTL. The client would provide the same `subscriptionId` on reconnect which should resolve on the server if it occurs within the TTL window and drain the buffered events. I imagine the websocket observability work could help with identifying a "reasonable" TTL as well as any sort of capacity planning in the buffering https://github.com/medplum/medplum/issues/4685. Ultimately, this seems not ideal as a reconnect outside the TTL could still result in dropped events (not to mention the ballooning complexity).

Defer to the Medplum team but this is likely a larger conversation worth bringing to https://github.com/medplum/medplum/discussions/1490

**Comment by ThatOneBro** [comment]
@dillonstreator Thanks for the input regarding requesting replays. Sorry for taking so long to respond to your thoughts.

I think it may be worth opening a discussion on that topic alone, since it would definitely be a nice QoL feature. Right now we are kind of going with a more fault-tolerant model that requires less knowledge on the serverside of the statefulness of a given subscription... given that we're expecting the volume and velocity of WebSocket subscription at scale to be pretty large. 

The idea about querying on disconnect via search is kind of what we're recommending for now. Check out how I did that in the new `BaseChat` implementation (although it's actually on reconnect): https://github.com/medplum/medplum/blob/cc661fc602ec475ed064b81f62d5b51b9ffb064f/packages/react/src/chat/BaseChat/BaseChat.tsx#L131

So I acknowledge this is less than ideal; having this done automatically would be awesome but we are a bit afraid of making WebSocket subscriptions a little too clever since it's still early days. 

We currently even delete the WebSocket `Subscription` resources on disconnect currently, and the client recreates the Subscriptions on reconnect since we are trying to make sure we don't get into too dirty of a state. Again, less than ideal and we definitely don't plan for this being the end state... but we want to get a little more data about usage patterns before we make any server-side changes and make the server-side implementation any heavier.

We do appreciate your input though, and again would love to open up more discussion on the dream state of the auto-replay functionality and how that might work
