### ISSUE TITLE
Investigate flaky tests for `AsyncJobExecutor`

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#4739]
* Can all promises/`then()` calls be converted to `async` and `await`?
* Can `start` and `run` be combined into single method?

**Comment by ThatOneBro** [comment]
I think `start` should be kept since it's able to do synchronous validation before kicking off the job and returning the corresponding response

We probably should partially revert to the previous model: 
https://github.com/medplum/medplum/blob/f7361ce40cfc2cc87976a72c7219e1b1dfc6105d/packages/server/src/fhir/operations/utils/asyncjobexecutor.ts#L41

**Comment by ThatOneBro** [comment]
Actually after closer inspection I think the previous code really only worked because of how things ended up in the event loop just in the right order to make sure that `updateResource` happened before the server close.

To do this more robustly, we probably have to track all `AsyncJob`s and wait for them to finish or timeout before closing the server as part of `shutdownApp()`

**Comment by codyebberson** [comment]
Hi @mattwiller  - This appears to be a side effect of https://github.com/medplum/medplum/pull/4558 - could you please take a look?  Thanks

**Comment by ThatOneBro** [comment]
Fixed in #4751 and #4826
