### ISSUE TITLE
`reorderBundle` w/ conditional references

### ISSUE THREAD

**Issue by dillonstreator** [medplum/medplum#5177]
I'm noticing an unexpected behavior of `reorderBundle` where it omits all entries not containing `fullUrl`. This behavior is clear from the implementation but the API doesn't make it obvious that this is what will happen. The documentation also doesn't make this super obvious, despite the alert being co-located with the `fullUrl` reference https://arc.net/l/quote/tcogmrdc. I'm leveraging conditional references and admittedly thought `reorderBundle` would resolve references in a similar way to `fullUrl`.
https://www.medplum.com/docs/migration/convert-to-fhir#linking-data-using-conditional-references

```ts
const bundle = reorderBundle({
  resourceType: 'Bundle',
  type: 'transaction',
  entry: [
    {
      resource: {
        resourceType: 'Task',
        code: {
          coding: [{ system: 'example.com/task-type', code: 'thing1' }],
        },
        status: 'ready',
        intent: 'order',
        for: {
          reference: 'Patient?identifier=example.com/patient|abc123',
        },
      },
      request: {
        method: 'POST',
        url: 'Patient',
        ifNoneExist: 'for:Patient.identifier=example.com/patient|abc123&code=example.com/task-type|thing1',
      },
    },
    {
      resource: {
        resourceType: 'Patient',
        identifier: [{ system: 'example.com/patient', value: 'abc123' }],
      },
      request: {
        method: 'POST',
        url: 'Patient',
        ifNoneExist: 'identifier?example.com/patient|abc123',
      },
    },
  ],
});
console.log(bundle); // { resourceType: 'Bundle', type: 'transaction', entry: [] }
```

Seems like it would be possible to support this behavior in `reorderBundle` w/ a more complex (cognitively & computationally) implementation. Curious - is there a desire or plans to support this?

**Comment by codyebberson** [comment]
@mattwiller  - can you confirm that this is fixed with the new batch system?

**Comment by mattwiller** [comment]
@dillonstreator Actually, that alert is no longer accurate after some recent changes to the Batch handling code; I went ahead and [updated the docs](https://github.com/medplum/medplum/pull/5340) to reflect this.  Additionally, there's an important difference: the `urn:uuid:` syntax is used to refer only to resources within the Bundle, and conditional references can only refer to already-created resources outside the Bundle.  In any case, it should no longer be necessary to call `reorderBundle()` before sending the JSON to the Batch API, since the new implementation handles reordering internally.
