### ISSUE TITLE
Allow using STU3 URLs for FHIRcast

### ISSUE THREAD

**Issue by sachin-sunny-rad** [medplum/medplum#5356]
We are trying to utilize the medplum client to interact with a third party fhircast hub which implements the STU3 spec where the hub topic can be defined in the body instead of being required on the url itself: https://hl7.org/fhir/uv/fhircast/2024May/2-6-RequestContextChange.html#request-context-change-example. Currently having to manually override the url:

```
  const { fetch: originalFetch } = window;

  window.fetch = async (...args) => {
    let [resource] = args;

    return await originalFetch(
      resource.toString().replace("fhircast/STU3", fhircastPrefix)
    );
  };
```

This should be supported if Medplum plans on supporting FHIR cast STU3: https://www.medplum.com/docs/fhircast. If this is already on the road map, apologies!

**Comment by ThatOneBro** [comment]
Hey Sachin,

Sorry about that. We were definitely cheating on our client implementation... I think the confusion arose around some of the earlier examples (before the latest May 2024 revision) containing a string that looked similar to the unique ID that is present in the `hub.channel.endpoint` but that seems to be an error on our part. 

Looks like we should have always supported it issued on `hub.url`, which is odd because this is definitely overloading `hub.url` with publish and subscription requests... but looks like that's the spec 😅 

So our proposed solution would be to:
1. Add a way to override `fhircastUrl` (it will default to our `fhircast/STU3`)
2. Make `fhircastPublish` directly publish to the `hub.url` (what we will call `fhircastUrl` in `MedplumClient`)
2. Make all FHIRcast methods make requests based off of `fhircastUrl` rather than the hardcoded `fhircast/STU3`

**Comment by sachin-sunny-rad** [comment]
No worries @ThatOneBro ! That solution should work for us. Thank you for getting back so quickly.
