### ISSUE TITLE
Cannot add Multiple Codes to Timing.Repeat.When of MedicationRequest

### ISSUE THREAD

**Issue by vilasvs03** [medplum/medplum#5378]
I wanted to add Multiple codes for When since It is an array of String, But System doesn't allow it.

**Use Case :** I want to place  a medication request with below details

- **Frequency :** 3 times a day (TID)
- **Frequency Period :** 1 day
- **When is :** MORN,NOON,NIGHT

**But when I try to do this, I get below Error Message:**
_Error evaluating invariant expression ({"fhirpath":"offset.empty() or (when.exists() and ((when in ('C' | 'CM' | 'CD' | 'CV')).not()))","error":{}}) (MedicationRequest.dosageInstruction[0].timing.repeat); Constraint tim-9 not met: If there's an offset, there must be a when (and not C, CM, CD, CV) ({"fhirpath":"offset.empty() or (when.exists() and ((when in ('C' | 'CM' | 'CD' | 'CV')).not()))"}) (MedicationRequest.dosageInstruction[0].timing.repeat)_

### RESOURCE JSON:

```json
{
  "resourceType": "MedicationRequest",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "123456",
        "display": "acne"
      }
    ],
    "text": "acne"
  },
  "status": "active",
  "intent": "order",
  "dosageInstruction": [
    {
      "text": "asdfghjkl",
      "route": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v3-RouteOfAdministration",
            "code": "PO",
            "display": "oral"
          }
        ]
      },
      "timing": {
        "repeat": {
          "frequency": 3,
          "period": 1,
          "periodUnit": "d",
          "when": [
            "MORN",
            "NOON",
            "NIGHT"
          ],
          "dayOfWeek": [
            "MON",
            "WED",
            "FRI"
          ]
        }
      },
      "additionalInstruction": [
        {
          "coding": [
            {
              "system": "http://hl7.org/fhir/r4/valueset-additional-instruction-codes",
              "code": "311501008",
              "display": "Before Food"
            }
          ]
        }
      ]
    }
  ],
  "requester": {
    "reference": "Practitioner/778e1bee-9bba-4cb1-99c8-bdd0e3e0cb54"
  },
  "subject": {
    "reference": "Patient/f91b9d1d-454d-4bed-a545-14e58034f4c6"
  },
  "encounter": {
    "reference": "Encounter/76c703af-8261-424c-9966-4dde387429a4"
  },
  "id": "07a246f0-d6ce-4c2d-8b65-8d4b41525924",
  "meta": {
    "project": "40da207b-9168-4e6b-990a-8d686ba4cbab",
    "compartment": [
      {
        "reference": "Project/40da207b-9168-4e6b-990a-8d686ba4cbab"
      },
      {
        "reference": "Patient/f91b9d1d-454d-4bed-a545-14e58034f4c6"
      }
    ],
    "versionId": "ef814e32-1bfc-4111-8578-72c3c85631f5",
    "lastUpdated": "2024-10-11T11:32:25.115Z",
    "author": {
      "reference": "Practitioner/778e1bee-9bba-4cb1-99c8-bdd0e3e0cb54",
      "display": "Vilas Shirodkar"
    }
  }
}
```

**Comment by codyebberson** [comment]
Hi @vilasvs03 - I think you found an interesting bug in the FHIR spec.

What's happening internally is that the Medplum FHIRPath engine is throwing an error when evaluating the `in` operator.

Here is the FHIRPath constraint:

https://hl7.org/fhir/R4/datatypes.html#Timing

![image](https://github.com/user-attachments/assets/b88c7512-7c9b-4c24-bc4f-7386777b4458)

Let's focus on this sub-expression:

```
(when in ('C' | 'CM' | 'CD' | 'CV')).not()
```

And here your `when` value is:

```json
"when": ["MORN", "NOON", "NIGHT"],
```

Logically that makes sense to me, and at first glance, I would say this should pass.

However, the FHIRPath engine is throwing an error because `when` is an array with more than one value, because that is in the spec:

https://hl7.org/fhirpath/#in-membership

"If the left operand has multiple items, an exception is thrown."

![image](https://github.com/user-attachments/assets/bcfa1bfc-9386-4fe9-8067-73d69419cbfa)

I suspect what the FHIR spec authors intended to say "must not contain any of these values", which probably should have been expressed using `contains` or `intersects` or something.

I will follow-up with our team on how to best proceed here.

**Comment by codyebberson** [comment]
This appears to have been fixed in R5.  We will test backporting the R5 FHIRPath constraint

```
offset.empty() or (when.exists() and when.select($this in ('C' | 'CM' | 'CD' | 'CV')).allFalse())
```

![image](https://github.com/user-attachments/assets/d43f9222-affa-424d-87a5-9a216e168da4)
