### ISSUE TITLE
api-extractor command error during build

### ISSUE THREAD

**Issue by Gary-Isaac** [medplum/medplum#5646]
Thanks for looking at this issue.

I am following the instructions on the https://www.medplum.com/docs/contributing/run-the-stack page. The npm run build:fast errors out (see second screenshot below) on the command to invoke api-extractor. I tried running the command directly from Powershell and Command Prompt. Both failed with not recognizing the api-extractor command. However, I'm unsure if running from the command line requires a different command than from the script. Do you have any ideas why the build script is failing?

I have installed the dependencies (node version 22) locally on Windows 11. Thanks!

![image](https://github.com/user-attachments/assets/7a0bff0d-6af9-49e0-ac23-28a670168cc5)

![image](https://github.com/user-attachments/assets/8d95eafa-7007-4869-ae6d-2a7aad5646ff)

**Comment by mattwiller** [comment]
@Gary-Isaac This issue actually appears to be due to the Linux-style command syntax with `&&` — both Command Prompt and Powershell don't support it.  You'll need to use Bash on Windows instead: we would recommend either the version [built in with Git](https://gitforwindows.org/) if you have that installed, or [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install)

**Comment by Gary-Isaac** [comment]
Thanks Matt! Building it from Git Bash solved the issue.




________________________________
